import 'package:get/get.dart';
import '../different_code/different_code.dart';

class AppCodeController extends GetxController {
  // Mobile Table = table in firestore that generated by mobile app
  // This tables reside in root.mobileTable.<appVid>.tables.<tableName>.content

  int applicationVid = 1212121212;  // default applicationVid
  int applicationTableVid = 1212121212; //

  void setApplicationVid() {
    applicationVid = defaultAppVid;
    applicationTableVid = tableVid;
    update();
  } // end of setApplicationVid
} // end of class AppCodeController