import 'dart:convert';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:get/get.dart';

import '../api.dart';
import '../crypto/auth_crypto.dart';
import '../different_code/different_code.dart';
import '../global.dart';

/// Split a possibly keyed table name into `(tableDocId, contentSubColl)`.
///
/// `getDocumentName`'s `//` folder form yields `<tableDocId>/<subColl>` (single
/// slash), e.g. `84214220504259/report-incident`, targeting a subcollection
/// parallel to `content`. Passing that straight to `.doc()` builds a 5-segment
/// (odd) path → Firestore "Invalid document reference" and wedges historySync.
/// Split so the table-definition doc uses `<tableDocId>` and rows land in the
/// named subcollection. A plain name keeps the default `content` subcollection.
///
/// The boundary is the LAST slash: `getDocumentName` sanitizes the subcoll part
/// to be slash-free, so any remaining slashes belong to a multi-level keyed name
/// (e.g. `$test/report-incident//sub` → `$test/report-incident/sub`). Firestore
/// doc IDs can't contain '/', so collapse them to '%' (getDocumentName's own
/// convention) into one valid segment — otherwise the extra segment lands in the
/// subcoll → 6-segment (even) `.collection()` → "collection path must point to a
/// valid collection".
(String, String) splitKeyedTableName(String tableName, String defaultSub) {
  final int slash = tableName.lastIndexOf('/');
  if (slash < 0) return (tableName, defaultSub);
  final String docId = tableName.substring(0, slash).replaceAll('/', '%');
  return (docId, tableName.substring(slash + 1));
}

class MobileTableController extends GetxController {
  // Mobile Table = table in firestore that generated by mobile app
  // This tables reside in root.mobileTable.<appVid>.tables.<tableName>.content
  final String mainCollectionName = mobileTable;
  final String tableCollectionName = mobileTableCollection;
  final String contentCollectionName = mobileTableContent;
  int applicationTableVid =
      appCodeController.applicationTableVid; // default applicationTableVid
  int tableRetention = 20160;
  String tableDescription = 'Default table for mobile app';
  String tableFlag = 'Default table flag';

  void setApplicationTableVid(int aVid) {
    applicationTableVid = aVid;
    update();
  } // end of setApplicationVid

  void setTableRetention(int inp) {
    tableRetention = inp;
    update();
  } // end of setTableRetention

  void setTableDescription(String inp) {
    tableDescription = inp;
    update();
  } // end of setTableDescription

  void setTableFlag(String inp) {
    tableFlag = inp;
    update();
  } // end of setTableFlag

  String getFinalCollection(String tableName) {
    // call this function :
    //  String finalCollection = Get.find<MobileTableController>().getFinalFinalCollection();
    return "$mainCollectionName.$applicationTableVid.$tableCollectionName.$tableName.$contentCollectionName";
  } // end of getFinalCollection

  Future<String> addContent(
    String tableName,
    String docContent,
    Map<String, dynamic>? indexField,
  ) async {
    // method for dynamic type of table
    String returnValue = 'Error';
    String applicationName = '$mainCollectionName/$applicationTableVid';
    String upperCollectionName = '$applicationName/$tableCollectionName';
    final (tableDocId, contentColl) = splitKeyedTableName(
      tableName,
      contentCollectionName,
    );
    CollectionReference mainCollectionRef = firestoreDb.collection(
      mainCollectionName,
    );
    DocumentSnapshot applicationSnapshot;
    String appVid = applicationTableVid.toString();
    try {
      // applicationSnapshot = await mainCollectionRef.doc(applicationVid).get();
      applicationSnapshot = await mainCollectionRef.doc(appVid).get();
      if (!applicationSnapshot.exists) {
        Map<String, dynamic> data = {'n': appName};
        await mainCollectionRef.doc(appVid).set(data);
        applicationSnapshot = await mainCollectionRef.doc(appVid).get();
      } // end if (!applicationSnapshot.exists)
      CollectionReference upperCollectionRef = firestoreDb.collection(
        upperCollectionName,
      );
      DocumentSnapshot tableSnapshot;
      try {
        tableSnapshot = await upperCollectionRef.doc(tableDocId).get();
        int nowMilli = getNowMillisecondFromEpoch();
        String checksum = getIntChecksum(
          sha3_256('${nowMilli.toString()}$docContent'),
        ).toString();
        String sep = separator[6]; // white star
        String sep2 = separator[1]; // black diamond
        List<dynamic> fields = jsonDecode(docContent);
        String header = '$checksum${sep}0$sep';
        String numberOfField = '00000${fields.length}';
        List<String> nameArray = tableName.split('.');
        if (nameArray.length < 2) {
          nameArray.add('mobileTable');
        } // end if (nameArray.length < 2)
        header += '${numberOfField.substring(numberOfField.length - 5)}$sep';
        header += '00200$sep{}$sep${nameArray[1]}$sep${nameArray[0]}';
        for (int i = 1; i <= fields.length; i++) {
          header += '$sep2$i${sep}text${sep}left';
        } // end for (int i=1 ; i<= table[0].length; i++)
        if (!tableSnapshot.exists) {
          Map<String, dynamic> data = {
            't': nowMilli,
            'cr': nowMilli,
            'd': tableDescription,
            'f': tableFlag,
            'r': tableRetention,
            'tt': 'D', // dynamic type, with 'content' collection in it
            'hd': header,
          };
          await upperCollectionRef.doc(tableDocId).set(data);
          applicationSnapshot = await upperCollectionRef.doc(tableDocId).get();
        } else {
          await upperCollectionRef.doc(tableDocId).update({'cr': nowMilli});
        } // end if (!tableSnapshot.exists)
        try {
          CollectionReference collectionRef = firestoreDb.collection(
            '$upperCollectionName/$tableDocId/$contentColl',
          );
          DocumentReference documentRef = collectionRef.doc();
          Map<String, dynamic> newData = indexField ?? {};
          newData['c'] = docContent;
          newData['t'] = getNowMillisecondFromEpoch();
          // todo create local data for offline mode, and retry at application start
          await documentRef.set(newData);
          String? header;
          // Read via data() map, NOT snapshot.get('hd'): .get() THROWS
          // "field hd does not exist" for a keyed-subcollection write whose
          // parent table doc was created elsewhere (no 'hd' header). The map
          // read returns null so the fallback below stamps a fresh checksum.
          final Map<String, dynamic>? tableDataMap =
              tableSnapshot.data() as Map<String, dynamic>?;
          header = tableDataMap?['hd'] as String?;
          if (header == null) {
            header = checksum;
          } else {
            // update checksum
            List<String> headerArray = header.split(separator[6]);
            if (headerArray.length < 2) {
              // Prior 'hd' has no star-separated structure — e.g. the bare
              // checksum written by the null-fallback above. Keyed-subcollection
              // writes share a parent doc whose 'hd' gets seeded that way, so a
              // sibling write reads it back here with only one slot: there is no
              // [1] to shift into. Reseed instead of indexing it (RangeError).
              header = checksum;
            } else {
              headerArray[1] = headerArray[0];
              headerArray[0] = checksum;
              // print ('headerArray = $headerArray. len=${headerArray.length}');
              String newHeader = headerArray[0];
              for (int i = 1; i < headerArray.length; i++) {
                newHeader += '${separator[6]}${headerArray[i]}';
              } // end for (int i=1; i<headerArray.length; i++)
              header = newHeader;
            }
          } //end if (header == null)

          safeFsUpdate(tableSnapshot.reference, {
            // update checksum of the table
            'hd': header,
          }, 'addContent-hd');
          // todo create flag 'sent' to local data
          returnValue = 'OK';
          update();
        } catch (e2) {
          returnValue += ' ${e2.toString()}';
        }
      } catch (e1) {
        returnValue += ' ${e1.toString()}';
      } // end try tableSnapshot
    } catch (e) {
      returnValue += ' ${e.toString()}';
    } // end try applicationSnapshot
    return returnValue;
  } // end of addContent

  Future<String> updateContent(
    String tableName,
    String searchField,
    dynamic searchValue,
    Map<int, String> partialFields, {
    Map<String, dynamic>? indexFieldUpdates,
  }) async {
    // Update existing row(s) in dynamic table by query.
    // - searchField: field name on the content doc (e.g. '3')
    // - searchValue: typed value (auto-detected: bool/num/string)
    // - partialFields: sparse 0-based map of column index → new value
    // - indexFieldUpdates: optional field updates for indexed columns whose
    //   values changed (only for columns that user explicitly patched).
    String returnValue = 'Error';
    String applicationName = '$mainCollectionName/$applicationTableVid';
    String upperCollectionName = '$applicationName/$tableCollectionName';
    try {
      final (tableDocId, contentColl) = splitKeyedTableName(
        tableName,
        contentCollectionName,
      );
      // Keyed // tables are always dynamic subcollection tables, but their
      // def-doc is created elsewhere and often lacks 'tt' (tt=null) — don't
      // reject them (mirrors readFromFirestoreTable's `|| isKeyed` gate).
      final bool isKeyed = contentColl != contentCollectionName;
      CollectionReference upperCollectionRef = firestoreDb.collection(
        upperCollectionName,
      );
      DocumentSnapshot tableSnapshot = await upperCollectionRef
          .doc(tableDocId)
          .get();
      if (!tableSnapshot.exists) {
        return 'Error: table not found';
      }
      Map<String, dynamic> tableData =
          tableSnapshot.data() as Map<String, dynamic>;
      if (tableData['tt'] != 'D' && !isKeyed) {
        return 'Error: update only supported for dynamic tables (tt=${tableData['tt']})';
      }

      String contentCollPath = '$upperCollectionName/$tableDocId/$contentColl';
      QuerySnapshot matches = await firestoreDb
          .collection(contentCollPath)
          .where(searchField, isEqualTo: searchValue)
          .get();

      if (matches.docs.isEmpty) {
        return 'Error: no match for $searchField=$searchValue';
      }

      int nowMilli = getNowMillisecondFromEpoch();
      int updatedCount = 0;

      for (DocumentSnapshot doc in matches.docs) {
        try {
          Map<String, dynamic> existing = doc.data() as Map<String, dynamic>;
          List<dynamic> currentRow = jsonDecode(existing['c'] ?? '[]');

          partialFields.forEach((idx, newValue) {
            if (idx < 0) return;
            while (currentRow.length <= idx) {
              currentRow.add('');
            }
            currentRow[idx] = newValue;
          });

          Map<String, dynamic> rowUpdate = {
            'c': jsonEncode(currentRow),
            't': nowMilli,
          };
          if (indexFieldUpdates != null && indexFieldUpdates.isNotEmpty) {
            rowUpdate.addAll(indexFieldUpdates);
          }
          partialFields.forEach((idx, newValue) {
            String colKey = (idx + 1).toString();
            if (rowUpdate.containsKey(colKey)) return;
            if (!existing.containsKey(colKey)) return;
            dynamic existingVal = existing[colKey];
            if (existingVal is bool) {
              rowUpdate[colKey] = newValue.toLowerCase() == 'true';
            } else if (existingVal is num) {
              rowUpdate[colKey] = num.tryParse(newValue);
            } else {
              rowUpdate[colKey] = newValue;
            }
          });
          await doc.reference.update(rowUpdate);
          updatedCount++;
        } catch (eRow) {
          returnValue += ' rowErr:${eRow.toString()}';
        }
      }

      String oldHeader = (tableData['hd'] ?? '') as String;
      String newChecksum = getIntChecksum(
        sha3_256('${nowMilli.toString()}u$updatedCount'),
      ).toString();
      String newHeader = _shiftHeaderChecksum(oldHeader, newChecksum);

      await tableSnapshot.reference.update({'cr': nowMilli, 'hd': newHeader});

      update();
      returnValue = 'OK $updatedCount updated';
    } catch (e) {
      returnValue += ' ${e.toString()}';
    }
    return returnValue;
  } // end of updateContent

  Future<String> deleteContent(
    String tableName,
    String searchField,
    dynamic searchValue,
  ) async {
    // Delete row(s) in dynamic table by query.
    String returnValue = 'Error';
    String applicationName = '$mainCollectionName/$applicationTableVid';
    String upperCollectionName = '$applicationName/$tableCollectionName';
    try {
      final (tableDocId, contentColl) = splitKeyedTableName(
        tableName,
        contentCollectionName,
      );
      final bool isKeyed = contentColl != contentCollectionName;
      CollectionReference upperCollectionRef = firestoreDb.collection(
        upperCollectionName,
      );
      DocumentSnapshot tableSnapshot = await upperCollectionRef
          .doc(tableDocId)
          .get();
      if (!tableSnapshot.exists) {
        return 'Error: table not found';
      }
      Map<String, dynamic> tableData =
          tableSnapshot.data() as Map<String, dynamic>;
      if (tableData['tt'] != 'D' && !isKeyed) {
        return 'Error: delete only supported for dynamic tables (tt=${tableData['tt']})';
      }

      String contentCollPath = '$upperCollectionName/$tableDocId/$contentColl';
      QuerySnapshot matches = await firestoreDb
          .collection(contentCollPath)
          .where(searchField, isEqualTo: searchValue)
          .get();

      if (matches.docs.isEmpty) {
        return 'Error: no match for $searchField=$searchValue';
      }

      int deletedCount = 0;
      for (DocumentSnapshot doc in matches.docs) {
        try {
          await doc.reference.delete();
          deletedCount++;
        } catch (eRow) {
          returnValue += ' rowErr:${eRow.toString()}';
        }
      }

      int nowMilli = getNowMillisecondFromEpoch();
      String oldHeader = (tableData['hd'] ?? '') as String;
      String newChecksum = getIntChecksum(
        sha3_256('${nowMilli.toString()}d$deletedCount'),
      ).toString();
      String newHeader = _shiftHeaderChecksum(oldHeader, newChecksum);

      await tableSnapshot.reference.update({'cr': nowMilli, 'hd': newHeader});

      update();
      returnValue = 'OK $deletedCount deleted';
    } catch (e) {
      returnValue += ' ${e.toString()}';
    }
    return returnValue;
  } // end of deleteContent

  String _shiftHeaderChecksum(String oldHeader, String newChecksum) {
    final String sep = separator[6]; // ☆ white star
    if (oldHeader.isEmpty) return newChecksum;
    List<String> parts = oldHeader.split(sep);
    if (parts.length < 2) {
      return '$newChecksum$sep${parts.isNotEmpty ? parts[0] : ''}';
    }
    parts[1] = parts[0];
    parts[0] = newChecksum;
    return parts.join(sep);
  } // end of _shiftHeaderChecksum
} // end of class MobileTableController
