import 'dart:convert';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:get/get.dart';
import '../crypto/auth_crypto.dart';
import '../different_code/different_code.dart';
import '../global.dart';
import '../api.dart';

class MobileTableController extends GetxController {
  // Mobile Table = table in firestore that generated by mobile app
  // This tables reside in root.mobileTable.<appVid>.tables.<tableName>.content
  final String mainCollectionName = mobileTable;
  final String tableCollectionName = mobileTableCollection;
  final String contentCollectionName = mobileTableContent;
  int applicationTableVid =
      appCodeController.applicationTableVid; // default applicationTableVid
  int tableRetention = 20160;
  String tableDescription = 'Default table for mobile app';
  String tableFlag = 'Default table flag';

  void setApplicationTableVid(int aVid) {
    applicationTableVid = aVid;
    update();
  } // end of setApplicationVid

  void setTableRetention(int inp) {
    tableRetention = inp;
    update();
  } // end of setTableRetention

  void setTableDescription(String inp) {
    tableDescription = inp;
    update();
  } // end of setTableDescription

  void setTableFlag(String inp) {
    tableFlag = inp;
    update();
  } // end of setTableFlag

  String getFinalCollection(String tableName) {
    // call this function :
    //  String finalCollection = Get.find<MobileTableController>().getFinalFinalCollection();
    return "$mainCollectionName.$applicationTableVid.$tableCollectionName.$tableName.$contentCollectionName";
  } // end of getFinalCollection

  Future<String> addContent(String tableName, String docContent,
      Map<String, dynamic>? indexField) async {
    // method for dynamic type of table
    String returnValue = 'Error';
    String applicationName = '$mainCollectionName/$applicationTableVid';
    String upperCollectionName = '$applicationName/$tableCollectionName';
    CollectionReference mainCollectionRef =
        firestoreDb.collection(mainCollectionName);
    DocumentSnapshot applicationSnapshot;
    String appVid = applicationTableVid.toString();
    try {
      // applicationSnapshot = await mainCollectionRef.doc(applicationVid).get();
      applicationSnapshot = await mainCollectionRef.doc(appVid).get();
      if (!applicationSnapshot.exists) {
        Map<String, dynamic> data = {'n': appName};
        await mainCollectionRef.doc(appVid).set(data);
        applicationSnapshot = await mainCollectionRef.doc(appVid).get();
      } // end if (!applicationSnapshot.exists)
      CollectionReference upperCollectionRef =
          firestoreDb.collection(upperCollectionName);
      DocumentSnapshot tableSnapshot;
      try {
        tableSnapshot = await upperCollectionRef.doc(tableName).get();
        int nowMilli = getNowMillisecondFromEpoch();
        String checksum =
            getIntChecksum(sha3_256('${nowMilli.toString()}$docContent'))
                .toString();
        String sep = separator[6]; // white star
        String sep2 = separator[1]; // black diamond
        List<dynamic> fields = jsonDecode(docContent);
        String header = '$checksum${sep}0$sep';
        String numberOfField = '00000${fields.length}';
        List<String> nameArray = tableName.split('.');
        if (nameArray.length < 2) {
          nameArray.add('mobileTable');
        } // end if (nameArray.length < 2)
        header += '${numberOfField.substring(numberOfField.length - 5)}$sep';
        header += '00200$sep{}$sep${nameArray[1]}$sep${nameArray[0]}';
        for (int i = 1; i <= fields.length; i++) {
          header += '$sep2$i${sep}text${sep}left';
        } // end for (int i=1 ; i<= table[0].length; i++)
        if (!tableSnapshot.exists) {
          Map<String, dynamic> data = {
            't': nowMilli,
            'cr': nowMilli,
            'd': tableDescription,
            'f': tableFlag,
            'r': tableRetention,
            'tt': 'D', // dynamic type, with 'content' collection in it
            'hd': header,
          };
          await upperCollectionRef.doc(tableName).set(data);
          applicationSnapshot = await upperCollectionRef.doc(tableName).get();
        } else {
          await upperCollectionRef.doc(tableName).update({
            'cr': nowMilli,
          });
        } // end if (!tableSnapshot.exists)
        try {
          CollectionReference collectionRef = firestoreDb.collection(
              '$upperCollectionName/$tableName/$contentCollectionName');
          DocumentReference documentRef = collectionRef.doc();
          Map<String, dynamic> newData = indexField ?? {};
          newData['c'] = docContent;
          newData['t'] = getNowMillisecondFromEpoch();
          // todo create local data for offline mode, and retry at application start
          await documentRef.set(newData);
          String? header;
          header = tableSnapshot.get('hd');
          if (header == null) {
            header = checksum;
          } else {
            // update checksum
            List<String> headerArray = (header ?? '').split(separator[6]);
            headerArray[1] = headerArray[0];
            headerArray[0] = checksum;
            // print ('headerArray = $headerArray. len=${headerArray.length}');
            String newHeader = headerArray[0] ?? '';
            for (int i = 1; i < headerArray.length; i++) {
              newHeader += '${separator[6]}${headerArray[i]}';
            } // end for (int i=1; i<headerArray.length; i++)
            header = newHeader;
          } //end if (header == null)

          tableSnapshot.reference.update({
            // update checksum of the table
            'hd': header,
          });
          // todo create flag 'sent' to local data
          returnValue = 'OK';
          update();
        } catch (e2) {
          returnValue += ' ${e2.toString()}';
        }
      } catch (e1) {
        returnValue += ' ${e1.toString()}';
      } // end try tableSnapshot
    } catch (e) {
      returnValue += ' ${e.toString()}';
    } // end try applicationSnapshot
    return returnValue;
  } // end of addContent
} // end of class MobileTableController
