// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByPxHl-KhJAlbtA4WLeWTRbUE6Tl-bxlk',
    appId: '1:721538991284:android:2df07d86167af7ec2d03e1',
    messagingSenderId: '721538991284',
    projectId: 'otq-01',
    databaseURL: 'https://otq-01.firebaseio.com',
    storageBucket: 'otq-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxrMU2CjKHt7FLKDhfU7x35oiUg6qbqzE',
    appId: '1:721538991284:ios:ebeaa1fdd0ea94ab2d03e1',
    messagingSenderId: '721538991284',
    projectId: 'otq-01',
    databaseURL: 'https://otq-01.firebaseio.com',
    storageBucket: 'otq-01.appspot.com',
    androidClientId: '721538991284-08a6f71qjhd18hcdp6jog3n2kjaticgh.apps.googleusercontent.com',
    iosClientId: '721538991284-lqq5e3jsm6g91gdeh2qo24tkjlu4bn0o.apps.googleusercontent.com',
    iosBundleId: 'com.autsorz.master1',
  );
}
